[toolchain]

[features]
seeds = true
skip-lint = false

[programs.mainnet]
bonk_paws = "bfpP4enQQ7ajSLaMWhAy6wYZYmRV6uxVid3r5hphh68"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "mainnet"
cluster = "https://attentive-frequent-darkness.solana-mainnet.quiknode.pro/5df866d1030f5bb9b9b95e95f1d5e3c41416ffcf/"
wallet = "/Users/elon/.config/solana/mainnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
